apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-internal-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-internal
  template:
    metadata:
      labels:
        app: product-internal
    spec:
      containers:
      - name: api
        image: albertsiempre/product-internal:latest
        ports:
        - containerPort: 9990
---
apiVersion: v1
kind: Service
metadata:
  name: product-internal-service
  labels:
    app: product-internal-service
spec:
  ports:
  - port: 80
    name: http
    targetPort: 9990
  selector:
    app: product-internal