apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: api-external
  annotations:
    kubernetes.io/ingress.class: kong
username: api-external
credentials:
  - app-external-jwt #secret name when creating jwt secret
  - app-external-acl #secret name when creating acl secret